name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated checkout action

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated setup-python action
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy psutil unittest-xml-reporting coverage

    - name: Run tests with coverage and logging
      run: |
        coverage run -m unittest discover -s . -p "test_*.py" | tee test_output.log
        coverage report
        coverage xml

    - name: Save test logs
      uses: actions/upload-artifact@v4  # ✅ Fixed deprecated action
      with:
        name: test-logs
        path: test_output.log

    - name: Upload coverage report
      uses: codecov/codecov-action@v4  # ✅ Ensure latest Codecov version
      with:
        file: ./coverage.xml
        flags: unittests
        name: python-codecov
